name: Question / Help
description: Ask a question or get help with LDF
title: "[Question]: "
labels: ["question", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Need help with LDF? We're happy to assist!

        **Tip:** For general questions and discussions, consider using [GitHub Discussions](https://github.com/LLMdotInfo/ldf/discussions) instead.

  - type: textarea
    id: question
    attributes:
      label: Question
      description: What do you need help with?
      placeholder: How do I...
    validations:
      required: true

  - type: textarea
    id: tried
    attributes:
      label: What I've Tried
      description: What steps have you already taken to find an answer?
      placeholder: |
        - Searched the documentation
        - Tried running `ldf --help`
        - Looked at existing issues
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Add any relevant code, configuration, or screenshots
    validations:
      required: false

  - type: input
    id: version
    attributes:
      label: LDF Version
      description: Output of `ldf --version` (if applicable)
      placeholder: "1.1.2"
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      options:
        - label: I have searched existing issues and discussions
          required: true
        - label: I agree to follow the project's Code of Conduct
          required: true
